name: pose_gallery_app
description: A premium Flutter app for PoseKW Gallery using Glassmorphism design.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & API
  http: ^1.1.0
  intl: ^0.20.2
  
  # UI & Design
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  screen_protector: ^1.2.0
  
  # Utilities
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.10
  path_provider: ^2.1.4
  path_provider_android: ^2.2.12
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.9
  
  # State Management (Simple provider or native ValueNotifier for now)
  provider: ^6.1.1
  device_preview: ^1.2.0
  
  # Notifications - REMOVED
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_v3.jpg"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

